### ISSUE TITLE
bullshit

### ISSUE THREAD

**Issue by Spacekoki** [IwasakiYuuki/2018_4J#1]
https://github.com/IwasakiYuuki/2018_4J/blob/a499030c9b8b34d3bd9c65a83fbb33523a62de9f/ke2/src/kadai_13.c#L54
F**K YOU YUUKI

**Comment by sakakendo0321** [comment]
oh my 👎

**Comment by Spacekoki** [comment]
U're NOOB
hahahahahaha
lolololololololol

**Comment by IwasakiYuuki** [comment]
ああ，そこ修正してからアップロードしなおすの忘れてた

**Comment by Spacekoki** [comment]
https://github.com/Spacekoki/Grade4/blob/master/ke2/ke2-13.c
My code is beautiful.
But your fuck'n code is fuck'n long.

**Comment by IwasakiYuuki** [comment]
if文一行で書くのよくないで

**Comment by IwasakiYuuki** [comment]
エラー出たときデバックするのめんどいぞ

**Comment by IwasakiYuuki** [comment]
てかお前のプログラム間違ってるで

**Comment by Spacekoki** [comment]
where

**Comment by IwasakiYuuki** [comment]
issue立てといたぞ
